backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### below lines for github backend, just in case. netlify works for now ###
  # name: github
  # repo: Astral1119/sheets-wiki

  # commit messages per https://decapcms.org/docs/configuration-options/
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”
    openAuthoring: '{{message}}'

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true

publish_mode: editorial_workflow

media_folder: "src/static/img"
public_folder: "/static/img"

site_url: https://sheets.wiki
display_url: https://sheets.wiki
logo_url: https://sheets.wiki/static/img/icon.svg

collections:
  - label: "Docs"
    name: "docs"
    folder: "src/docs/posts"
    create: true
    editor:
      preview: false
    slug: "{{short | slugify}}"
    preview_path: "{{slug}}"
    summary: "{{short}} - {{commit_date}} - {{commit_author}} - "
    sortable_fields: ['commit_date', 'short', 'commit_author']

    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Short Title", name: "short", widget: "string" }
      - { label: "Permalink (/permalink/)", name: "permalink", widget: "string", pattern: ['/[\w-\d]+/', "Must begin and end with / and only contain numbers, letters, and hyphens"] }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
     
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["function", "technique", "data-type"]

  - label: "Blog"
    name: "blog"
    folder: "src/blog/posts"
    create: true
    editor:
      preview: false
    preview_path: blog/posts/{{slug}}
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["algorithm", "game", "tutorial"]