backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### below lines for github backend, just in case. netlify works for now ###
  # name: github
  # repo: Astral1119/sheets-wiki

  # commit messages per https://decapcms.org/docs/configuration-options/
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”
    openAuthoring: '{{message}}'

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true

publish_mode: editorial_workflow

media_folder: "src/static/img"
public_folder: "/static/img"

site_url: https://sheets.wiki
display_url: https://sheets.wiki
logo_url: https://sheets.wiki/static/img/icon.svg

collections:
  - name: "pages"
    label: "Pages"
    folder: "src/pages"
    create: true
    editor:
      preview: false
    slug: "{{short | slugify}}"
    preview_path: "{{slug}}"
    sortable_fields: ['commit_date', 'short', 'commit_author']

    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Short Title", name: "short", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
  
  
  - name: "books"
    label: "Books"
    folder: "src/books"
    create: true
    editor:
      preview: false
    preview_path: "books/{{slug}}"
    sortable_fields: ['commit_date', 'short', 'commit_author']

    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - label: "Shelves"
        name: "shelves"
        widget: "list"
        collapsed: "true"
        field: {label: Shelf, name: shelf, widget: string}
      - { label: "Body", name: "body", widget: "markdown" }
      - label: Structure
        name: items
        widget: 'list'
        types:
          - label: Page
            name: page
            widget: object
            fields:
              - { label: Page, name: page, widget: string, default: 'slug, i.e. levenshtein-distance' }
          - label: Chapter
            name: chapter
            widget: list
            fields:
              - { label: Name, name: name, widget: string, default: 'Chapter Name' }
              - label: "Pages"
                name: "pages"
                widget: list
                field: { label: Page, name: page, widget: string }
                min: 1